[tasks.check]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.check-change]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.full]
dependencies = ["check-change", "build", "test"]

[tasks.clean-full]
dependencies = ["clean", "full"]
