version: 2.1

jobs:
  test:
    docker:
      - image: mariorgzlpz/arbitragebets
    steps:
      - checkout
      - run:
          name: Ejecuta tests
          command: cargo make test

workflows:
  version: 2
  test-workflow:
    jobs:
      - test