version: 2.1

jobs:
  test:
    docker:
      - image: mariorgzlpz/arbitragebets
    steps:
      - checkout
      - run:
          name: Establecer ruta para nextest
          command: |
            grep -q "dir" .config/nextest.toml; then
              sed -i 's|dir =.*|dir = "/home/circleci/target/nextest"|' .config/nextest.toml
      - run:
          name: Ejecuta tests
          command: cargo make test

workflows:
  version: 2
  test-workflow:
    jobs:
      - test