name: "Test Rust Project"
on:
  push:
  pull_request:

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: cargo-make, cargo-nextest
      - run: cargo make test