name: "Test Rust Project"
on:
  push:
  pull_request:

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: ["1.81.0", "1.82.0", "1.83.0"]
    steps:
      - name: Set up Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install cargo-make
        uses: baptiste0928/cargo-install@v1
        with:
          crate: make
          args: --locked
      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-nextest
          args: --locked 
      - name: Run Tests
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: test   